name: Actualizar avisos AEMET

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Actualizar Firestore
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
        run: npm start
